### ISSUE TITLE
adding new source doesn't create UI element

### ISSUE THREAD

**Issue by drmbt** [matthewwachter/td-sourcerer#1]
I like your system, and what works seems to work great. Unfortunately, I can't seem to create any new sources from the build that is up; clicking the  + does seem to store them somewhere, but no new buttons populate the left hand menu. possible a bug in 2020, just figured I'd let you know that it isn't currently working.

**Comment by matthewwachter** [comment]
Thanks for letting me know! I'll take a look.

**Comment by matthewwachter** [comment]
The issue is that the dependency between a python expression in the 'rows' parameter of the List COMP that references list of sources is somehow lost when the scene is reloaded. This wasn't the case in TouchDesigner version 2019.20140. 

I submitted the bug report to Derivative so we'll see what they say but I'll post a fix if it will be a while before the next official release.

**Comment by matthewwachter** [comment]
This issue has been resolved.
